spring:
  application:
    name: javaFinal

  datasource:
    url: jdbc:postgresql://localhost:5432/university_management_db
    username: postgres
    password: 1111

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

app:
  jwt:
    secret: bXktc3VwZXItc2VjcmV0LWtleS1mb3Itand0LXBhbjEtZWR1YXJkLTEyMzQ1Njc4OTA=
    expiration-ms: 86400000

file:
  upload-dir: uploads